# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd93ebe3981a1afaa92a274d3341fd1ea6a847a25a5b1690a8aadca9806bd6598c14457a0fe0e1da9e1a64dba1e493b2cd1d8f8b435a03d5cd9418fdc5c41e7

test:
  secret_key_base: 66ec05d01cb0886caa61c37fd626602a3fc8a35b987b0955c68992285efab66ab8605d5903b9e8d971fd88e19ed2495add9b198b17515503b2a72816a1f4c26a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
